baseURL = 'https://this-old.dad/'
languageCode = 'en-us'
title = "More fun than one guy should have"
disableKinds = ['taxonomy', 'term', 'rss']

[params]
  description = "Dogs, Food, Home Automation"
  author = "Scott"
